# Generated by Django 5.2.7 on 2025-10-14 16:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_arrival_time', models.TimeField(default=datetime.time(8, 0), verbose_name="Heure d'arrivée attendue")),
                ('expected_departure_time', models.TimeField(default=datetime.time(17, 0), verbose_name='Heure de départ attendue')),
                ('break_duration_minutes', models.IntegerField(default=60, verbose_name='Durée pause (minutes)')),
                ('tolerance_minutes', models.IntegerField(default=15, verbose_name='Tolérance retard (minutes)')),
                ('working_days', models.CharField(default='1,2,3,4,5', max_length=20, verbose_name='Jours travaillés (1=Lundi, 7=Dimanche)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres pointage',
                'verbose_name_plural': 'Paramètres pointage',
                'db_table': 'pointage_settings',
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('sick_leave', 'Congé maladie'), ('vacation', 'Congé payé'), ('personal', 'Congé personnel'), ('maternity', 'Congé maternité'), ('other', 'Autre')], max_length=20, verbose_name="Type d'absence")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(verbose_name='Raison')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('approval_notes', models.TextField(blank=True, null=True, verbose_name="Notes d'approbation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'developer'}, on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
                'db_table': 'absence_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Début pause')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Fin pause')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('late_reason', models.TextField(blank=True, null=True, verbose_name='Raison du retard')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_late', models.BooleanField(default=False, verbose_name='En retard')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Minutes de retard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'developer'}, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'pointages',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
