# Generated by Django 5.2.7 on 2025-10-28 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Notes d'approbation"),
        ),
        migrations.AddField(
            model_name='pointage',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pointages', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='arrival_status',
            field=models.CharField(blank=True, choices=[('on_time', "À l'heure"), ('late', 'En retard'), ('early', 'En avance')], max_length=10, null=True, verbose_name='Statut arrivée'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='departure_status',
            field=models.CharField(blank=True, choices=[('on_time', "À l'heure"), ('late', 'En retard'), ('early', 'En avance')], max_length=10, null=True, verbose_name='Statut départ'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='early_arrival_minutes',
            field=models.IntegerField(default=0, verbose_name="Minutes d'arrivée anticipée"),
        ),
        migrations.AddField(
            model_name='pointage',
            name='early_arrival_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Notes d'arrivée anticipée"),
        ),
        migrations.AddField(
            model_name='pointage',
            name='early_departure_minutes',
            field=models.IntegerField(default=0, verbose_name='Minutes de départ anticipé'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='early_departure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du départ anticipé'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='is_justified',
            field=models.BooleanField(default=False, verbose_name='Justifié'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='justification_approved',
            field=models.BooleanField(null=True, verbose_name='Justification approuvée'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='En retard (déprécié)'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes (déprécié)'),
        ),
    ]
