# Generated by Django 5.2.7 on 2025-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_pointage_approval_notes_pointage_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='total_work_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures travaillées'),
        ),
    ]
